package com.gameloft9.demo.dataaccess.dao.system;

import com.gameloft9.demo.dataaccess.model.system.SysMenuRoleTest;
import com.gameloft9.demo.dataaccess.model.system.SysMenuTest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysMenuRoleTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int insert(SysMenuRoleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int insertSelective(SysMenuRoleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    SysMenuRoleTest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int updateByPrimaryKeySelective(SysMenuRoleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_MENU_ROLE_TEST
     *
     * @mbggenerated Wed Dec 06 18:29:27 CST 2017
     */
    int updateByPrimaryKey(SysMenuRoleTest record);

    /**
     * 根据角色获取可见菜单列表
     * @param roleIds 角色id列表
     * */
    List<SysMenuTest> getDistinctMenusByRoleIds(List<String> roleIds);

    /**
     * 根据菜单id删除记录
     * @param menuId 菜单id
     */
    int deleteByMenuId(@Param("menuId") String menuId);

    /**
     * 根据菜单id和角色Id获取记录
     * @param menuId 菜单id
     * @param roleId 角色id
     * */
    SysMenuRoleTest selectByMenuIdAndRoleId(@Param("menuId") String menuId,
                                            @Param("roleId") String roleId);

    /**
     * 获取菜单对应的角色id列表
     * @param menuId 菜单id
     * */
    List<String> getRoleIdsByMenuId(@Param("menuId") String menuId);
}