package com.gameloft9.demo.dataaccess.dao.system;

import com.gameloft9.demo.dataaccess.model.system.SysOrganizeTest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysOrganizeTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int insert(SysOrganizeTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int insertSelective(SysOrganizeTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    SysOrganizeTest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int updateByPrimaryKeySelective(SysOrganizeTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int updateByPrimaryKey(SysOrganizeTest record);


    /**
     * 获取所有组织机构
     * */
    List<SysOrganizeTest> getAll();

    /**
     * 获取子机构个数
     * @param parentId 父机构id
     * */
    int countChildren(@Param("parentId") String parentId);

    /**
     * 根据名称获取组织机构
     * @param orgName 组织机构名称
     * */
    SysOrganizeTest getByName(@Param("orgName") String orgName);

    /**
     * 获取根组织机构
     * */
    SysOrganizeTest getRoot();

    /**
     * 找到某一层机构最大序号
     * @param level 机构层级
     * */
    String getMaxOrgCode(@Param("level") int level);
}