package com.gameloft9.demo.dataaccess.dao.system;

import com.gameloft9.demo.dataaccess.model.system.SysRoleTest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysRoleTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int insert(SysRoleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int insertSelective(SysRoleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    SysRoleTest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int updateByPrimaryKeySelective(SysRoleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_TEST
     *
     * @mbggenerated Mon Dec 04 11:17:05 CST 2017
     */
    int updateByPrimaryKey(SysRoleTest record);

    /**
     * 获取所有角色
     * @param start 开始
     * @param end 结束
     * */
    List<SysRoleTest> selectAll(
            @Param("start") int start,
            @Param("end") int end,
            @Param("roleName") String roleName,
            @Param("isSuper") String isSuper);


    /**
     * 获取所有角色个数
     * */
    int countGetAll( @Param("roleName") String roleName,
                     @Param("isSuper") String isSuper);

    /**
     * 根据角色名称获取记录
     * @param roleName 角色名称
     * */
    SysRoleTest getByRoleName(@Param("roleName") String roleName);

    /**
     * 根据id获取角色列表
     * @param ids id列表
     * */
    List<String> getRoleNamesByIds(@Param("ids") List<String> ids);
}