
CREATE TABLE SYS_OPER_LOG_TEST
(
  ID          VARCHAR2(32)                 NOT NULL,
  USER_ID     VARCHAR2(32),
  LOGIN_NAME  VARCHAR2(32),
  IP_ADDR     VARCHAR2(64),
  OPER_TYPE   VARCHAR2(200),
  CREATE_DATE DATE,
  MEMO        VARCHAR2(1500)
)

ALTER TABLE SYS_OPER_LOG_TEST ADD CONSTRAINT PK_LOG_ID PRIMARY KEY (ID)