--测试表
DROP TABLE USER_TEST CASCADE CONSTRAINTS;

CREATE TABLE USER_TEST
(
  ID               VARCHAR2(32)  NOT NULL,
  LOGIN_NAME       VARCHAR2(10),
  PASSWORD         VARCHAR2(128),
  REAL_NAME        VARCHAR2(50),
  IS_FORBIDDEN     VARCHAR2(1),
  MOBILE           VARCHAR2(11),
  ICON             VARCHAR2(200),
  ORG_ID           VARCHAR2(32),
  ORG_NAME         VARCHAR2(50),
  CREATE_DATE      DATE DEFAULT  sysdate,
  UPDATE_DATE      DATE DEFAULT  sysdate
)

ALTER TABLE USER_TEST ADD CONSTRAINT PK_USER_ID PRIMARY KEY (ID)

create UNIQUE index uidx_login_name on USER_TEST(LOGIN_NAME)
