DROP TABLE SYS_USER_ROLE_TEST CASCADE CONSTRAINTS;

CREATE TABLE SYS_USER_ROLE_TEST
(
  ID       VARCHAR2(32)                    NOT NULL,
  USER_ID  VARCHAR2(32),
  ROLE_ID  VARCHAR2(32)
)

COMMENT ON TABLE SYS_USER_ROLE_TEST IS '用户角色表';
COMMENT ON COLUMN SYS_USER_ROLE_TEST.ID IS '主键';
COMMENT ON COLUMN SYS_USER_ROLE_TEST.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_USER_ROLE_TEST.ROLE_ID IS '角色ID';

ALTER TABLE SYS_USER_ROLE_TEST ADD CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID)