DROP TABLE SYS_ORGANIZE_TEST CASCADE CONSTRAINTS;

CREATE TABLE SYS_ORGANIZE_TEST
(
  ID                    VARCHAR2(32)                  NOT NULL,
  PARENT_ID             VARCHAR2(32),
  ORGANIZE_NAME         VARCHAR2(255)      NOT NULL,
  ORGANIZE_CODE         VARCHAR2(8)        NOT NULL,
  TREE_LEVEL            NUMBER             NOT NULL,
  TREE_PATH             VARCHAR2(200),
  CREATE_DATE            DATE                   DEFAULT SYSDATE,
  UPDATE_DATE            DATE                   DEFAULT SYSDATE
)

ALTER TABLE SYS_ORGANIZE_TEST ADD CONSTRAINT PK_SYS_ORGANIZE PRIMARY KEY (ID)

create UNIQUE index uidx_org_name on SYS_ORGANIZE_TEST(ORGANIZE_NAME)
create UNIQUE index uidx_org_code on SYS_ORGANIZE_TEST(ORGANIZE_CODE)

COMMENT ON TABLE SYS_ORGANIZE_TEST IS '组织机构表';
COMMENT ON COLUMN SYS_ORGANIZE_TEST.ORGANIZE_NAME IS '机构名称';
COMMENT ON COLUMN SYS_ORGANIZE_TEST.ORGANIZE_CODE IS '机构编码';
COMMENT ON COLUMN SYS_ORGANIZE_TEST.TREE_PATH IS '机构路径';
