DROP TABLE SYS_MENU_ROLE_TEST CASCADE CONSTRAINTS;

CREATE TABLE SYS_MENU_ROLE_TEST
(
  ID           VARCHAR2(32)                NOT NULL,
  MENU_ID      VARCHAR2(32),
  ROLE_ID      VARCHAR2(32),
  CREATE_USER  VARCHAR2(32),
  CREATE_TIME  TIMESTAMP(6)                     DEFAULT SYSDATE,
  UPDATE_USER  VARCHAR2(32),
  UPDATE_TIME  TIMESTAMP(6)                     DEFAULT SYSDATE
)

COMMENT ON TABLE SYS_MENU_ROLE_TEST IS '菜单角色表';
COMMENT ON COLUMN SYS_MENU_ROLE_TEST.MENU_ID IS '菜单id';
COMMENT ON COLUMN SYS_MENU_ROLE_TEST.ROLE_ID IS '角色id';


ALTER TABLE SYS_MENU_ROLE_TEST ADD CONSTRAINT PK_MENU_ROLE_ID PRIMARY KEY (ID)

create UNIQUE index uidx_menu_role on SYS_MENU_ROLE_TEST(MENU_ID,ROLE_ID)
