DROP TABLE SYS_MENU_TEST CASCADE CONSTRAINTS;

CREATE TABLE SYS_MENU_TEST
(
  ID           VARCHAR2(32)                NOT NULL,
  TITLE        VARCHAR2(100)               NOT NULL,
  HREF         VARCHAR2(200)               NOT NULL,
  REQUEST_URL  VARCHAR2(200),
  ICON         VARCHAR2(50),
  CODE         VARCHAR2(100),
  TARGET       VARCHAR2(50),
  PARENT_ID    VARCHAR2(32),
  SORT         NUMBER,
  CREATE_USER  VARCHAR2(32),
  CREATE_TIME  TIMESTAMP(6)                     DEFAULT SYSDATE,
  UPDATE_USER  VARCHAR2(32),
  UPDATE_TIME  TIMESTAMP(6)                     DEFAULT SYSDATE
)

COMMENT ON TABLE SYS_MENU_TEST IS '基本菜单表';
COMMENT ON COLUMN SYS_MENU_TEST.TITLE IS '菜单名称';
COMMENT ON COLUMN SYS_MENU_TEST.HREF IS '访问链接';
COMMENT ON COLUMN SYS_MENU_TEST.REQUEST_URL IS '后台请求url';
COMMENT ON COLUMN SYS_MENU_TEST.CODE IS '菜单编码';
COMMENT ON COLUMN SYS_MENU_TEST.ICON IS '菜单图标';
COMMENT ON COLUMN SYS_MENU_TEST.TARGET IS '目标窗口,_blank则直接跳转，否则在子页面打开';
COMMENT ON COLUMN SYS_MENU_TEST.PARENT_ID IS '父菜单';
COMMENT ON COLUMN SYS_MENU_TEST.SORT IS '排序号';


ALTER TABLE SYS_MENU_TEST ADD CONSTRAINT PK_MENU_ID PRIMARY KEY (ID)

create UNIQUE index uidx_title on SYS_MENU_TEST(title)

create unique index uidx_menu_req_url on SYS_MENU_TEST (request_url)
