DROP TABLE SYS_ROLE_TEST CASCADE CONSTRAINTS;

CREATE TABLE SYS_ROLE_TEST
(
  ID           VARCHAR2(32)                      NOT NULL,
  ROLE_NAME    VARCHAR2(50)                      not null,
  IS_SUPER     VARCHAR2(1)                        DEFAULT 0,
  IS_DELETED   VARCHAR2(1)                        DEFAULT 0,
  CREATE_USER  VARCHAR2(50),
  CREATE_TIME  TIMESTAMP(6)                     DEFAULT SYSDATE,
  UPDATE_USER  VARCHAR2(50),
  UPDATE_TIME  TIMESTAMP(6)                     DEFAULT SYSDATE
)

ALTER TABLE SYS_ROLE_TEST ADD CONSTRAINT PK_ROLE PRIMARY KEY (ID)

COMMENT ON TABLE SYS_ROLE_TEST IS '角色表';

COMMENT ON COLUMN SYS_ROLE_TEST.ROLE_NAME IS '角色名';

COMMENT ON COLUMN SYS_ROLE_TEST.IS_SUPER IS '是否是超级管理员';

COMMENT ON COLUMN SYS_ROLE_TEST.IS_DELETED IS '是否删除';

COMMENT ON COLUMN SYS_ROLE_TEST.CREATE_USER IS '创建用户';

COMMENT ON COLUMN SYS_ROLE_TEST.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN SYS_ROLE_TEST.UPDATE_USER IS '更新用户';

COMMENT ON COLUMN SYS_ROLE.UPDATE_TIME IS '更新时间';

